export const EXERCISE_LIST = [
  {
    name: "Жим лёжа",
    muscleGroup: "chest",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Становая тяга",
    muscleGroup: "back",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Приседания со штангой",
    muscleGroup: "quads",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Подтягивания",
    muscleGroup: "back",
    type: "own weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Армейский жим",
    muscleGroup: "delts",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Сгибания на бицепс",
    muscleGroup: "biceps",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Французский жим",
    muscleGroup: "triceps",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Разгибания ног в тренажёре",
    muscleGroup: "quads",
    type: "machine",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Сгибания ног в тренажёре",
    muscleGroup: "hamstrings",
    type: "machine",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Тяга верхнего блока",
    muscleGroup: "back",
    type: "machine",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Жим ногами",
    muscleGroup: "quads",
    type: "machine",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Отжимания на брусьях",
    muscleGroup: "triceps",
    type: "own weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Махи гантелями в стороны",
    muscleGroup: "delts",
    type: "free weight",
    unilateral: false,
    amplitude: "full",
  },
  {
    name: "Скручивания",
    muscleGroup: "abs",
    type: "own weight",
    unilateral: false,
    amplitude: "full",
  },
  // ... добавь ещё по желанию
];
