export const translations = {
  english: {
    // Settings
    theme: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
    weight: "Weight (kg)",
    enterWeight: "Enter weight",
    developerMode: "Developer mode",
    importData: "Import data",
    migrateFromOldVersion: "Migrate from old version",
    language: "Language",
    maxMicrohistorySize: "Max microhistory size",
    microhistoryDescription: "Write more if you do more sets",
    analyticsSettings: "Analytics settings",
    visibleMetrics: "Visible metrics",
    generalTonnage: "General tonnage",
    specificTonnage: "Specific tonnage",
    maxWeight: "Max weight",
    maxReps: "Max reps",
    avgWeight: "Average weight",
    minWeight: "Min weight",
    workoutTime: "Workout time",
    predicted1rm: "Predicted 1RM",
    muscleCoefficients: "Soreness coefficients. Set more if you experience severe soreness",
    chest: "Chest",
    back: "Back",
    biceps: "Biceps",
    triceps: "Triceps",
    delts: "Delts",
    legs: "Legs",

    // Calories
    calories: "Calories",
    caloriesPerDay: "Calories per day",
    enterCalories: "Enter calories",
    yourWeight: "Your weight (kg)",
    enterYourWeight: "Enter your weight",
    save: "Save",
    today: "Today:",
    caloriesValue: "Calories: {value} kcal",
    weightValue: "Weight: {value} kg",
    caloriesAndWeightChart: "Calories and weight chart",
    error: "Error",
    fillAllFields: "Fill all fields",
    enterValidCalories: "Enter valid calories",
    enterValidWeight: "Enter valid weight",
    success: "Success",
    dataSaved: "Data saved",

    // Workout Plan
    selectPlan: "Select plan",
    noWorkoutsInPlan: "No workouts in plan",
    selectPlanToStart: "Select plan to start",
    addWorkout: "+ Add workout",
    workoutName: "Workout name",
    enterName: "Enter name",
    cancel: "Cancel",
    add: "Add",
    resultsPlanning: "Results planning",

    // Analytics
    selectExercises: "Select exercises",
    selected: "Selected: {count} exercises",
    date: "Date",
    tonnage: "Tonnage",
    weightLabel: "Weight",
    reps: "Reps",
    minutes: "Minutes",
    t: "t",
    exercise: "Exercise",
    max: "Max",
    trend: "Trend",
    rel: "%",

    // Plan Screen
    addPlannedResult: "Add planned result",
    weightKg: "Weight (kg)",
    repetitions: "Repetitions",
    dateWithinMonth: "Date (YYYY-MM-DD)",
    saveResult: "Save",
    monthLabel: "MMMM YYYY",

    // Workout Screen
    editExercise: "Edit exercise",
    addExercise: "Add exercise",
    exerciseName: "Exercise name",
    comment: "Comment",
    timerDurationSec: "Timer duration (sec)",
    muscleGroup: "Muscle group",
    exerciseType: "Exercise type",
    fullAmplitude: "Full amplitude",
    partialAmplitude: "Partial amplitude",
    unilateral: "Unilateral",
    bilateral: "Bilateral",
    machine: "Machine",
    freeWeight: "Free weight",
    ownWeight: "Own weight",
    cables: "Cables",
    forearms: "Forearms",
    glutes: "Glutes",
    quads: "Quads",
    hamstrings: "Hamstrings",
    calves: "Calves",
    abs: "Abs",
    selectExercise: "Select exercise",

    // Plan Selector
    choosePlan: "Choose plan",
    addPlan: "Add plan",
    newPlan: "New plan",
    planName: "Plan name",
    workoutsCount: "{count} workouts",

    // Exercise Component
    kg: "kg",
    repsUnit: "reps",
    unilateralExercise: "Unilateral",
    bilateralExercise: "Bilateral",
    fullAmplitudeExercise: "Full amplitude",
    partialAmplitudeExercise: "Partial amplitude",

    // Common
    loading: "Loading...",
    loadingData: "Loading data...",
    errorOccurred: "An error occurred",
    tryAgain: "Try again",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    close: "Close",

    // Import Screen
    pasteTextForImport: "Paste text for import:",
    selectFile: "Select file",
    import: "Import",
    dataImportSuccess: "Data imported successfully",
    dataImportError: "Failed to import data",
    fileOpenError: "Failed to open file",
    validationError: "Text validation failed",
    importFormatExample: `Paste data in format:

Bench press
60x8 60x7 60x6 01.02.2025
65x8 65x7 65x6 01.03.2025

Pull-ups
10x5 12x4 15x3 01.02.2025

`,

    // Import Validator
    validationErrorTitle: "Validation error",
    warningTitle: "Warning",

    // Exercise Modal
    chooseExercise: "Choose exercise",
    timerDuration: "Timer duration (sec)",

    // Exercise Component
    weightPlaceholder: "Weight",
    repsPlaceholder: "Repetitions",

    // Analytics Exercise Selector

    // Tab Navigation
    home: "Home",
    caloriesTab: "Calories",
    workout: "Workout",
    storage: "Storage",
    plan: "Plan",
    analytics: "Analytics",
    settings: "Settings",

    // Export
    exportData: "Export data",
    exportDescription: "Choose the format to export your data:",
    exportToExcel: "Export to Excel",
    exportToText: "Export to Text",
    exportToPDF: "Export to PDF",
    excelDescription:
      "Excel file with multiple sheets (plans, results, calories)",
    textDescription: "Text file in custom format",
    pdfDescription: "PDF report with charts and metrics",
    totalSets: "Total sets",
    dataExportSuccess: "Data exported successfully",
    dataExportError: "Failed to export data",
    exporting: "Exporting...",
    notEnoughDataForPDF: "Need at least 10 different dates to export PDF",

    // Maintenance Calories
    maintenanceCalories: "Maintenance Calories",
    maintenanceCaloriesPerDay: "Calories to maintain weight",
    enterMaintenanceCalories: "Enter maintenance calories",
    maintenanceCaloriesSaved: "Maintenance calories saved",
    enterValidMaintenanceCalories: "Enter valid maintenance calories",
    maintenanceCaloriesValue: "Maintenance calories: {value} kcal",
    deviationFromMaintenance: "Deviation from maintenance: {value} kcal",
    change: "Change",
    avgVolume: "Average weekly training volume",
    avgTonnageProgress: "Average tonnage progress",
    avgWeightProgress: "Average max weight progress",
    caloriesUp: "Calories (upper)",
    weightDown: "Weight (bottom)",
    absMax: "Absolute max weight",
    trainingSettings: "Training settings",

    // Comparison objects for total tonnage
    smallAircraftEngine: "Small aircraft engine",
    piano: "Piano",
    fiat500: "Fiat 500",
    safe: "Safe",
    smartFortwo: "Smart Fortwo",
    ladaGranta: "Lada Granta",
    boeing737Engine: "Boeing 737 engine",
    mazWithCargo: "MAZ with cargo",
    fordF150: "Ford F-150",
    hummerH1: "Hummer H1",
    kamaz4326: "Kamaz-4326",
    pazBus: "PAZ bus",
    garbageTruck: "Garbage truck",
    trolleybus: "Trolleybus",
    bmd4: "BMD-4",
    btr80: "BTR-80",
    bmp2: "BMP-2",
    dumpTruckLoaded: "Dump truck loaded",
    t34_76: "T-34/76 tank",
    c130HerculesEmpty: "C-130 Hercules empty",
    metroCarEmpty: "Metro car empty",
    stonehenge: "Stonehenge",
    t90: "T-90 tank",
    boeing757Empty: "Boeing 757 empty",
    leopard2: "Leopard 2 tank",
    tigerII: "Tiger II tank",
    boeing767Empty: "Boeing 767 empty",
    coalWagonLoaded: "Coal wagon loaded",
    bulldozerCatD11: "Bulldozer CAT D11",
    tep70Locomotive: "TEP70 locomotive",
    trireme: "Trireme",
    an124Empty: "An-124 Ruslan empty",
    boeing747Empty: "Boeing 747 empty",
    mausTank: "Maus tank",
    spacexStarshipPrototype: "SpaceX Starship prototype",
    statueOfLibertyCopper: "Statue of Liberty copper",
    an225Empty: "An-225 Mriya empty",
    metroTrain6CarsLoaded: "Metro train 6 cars loaded",
    boeing747MaxTakeoff: "Boeing 747 max takeoff",
    smallSubmarine: "Small submarine",
    smallOilPlatform: "Small oil platform",
    statueOfUnityFrame: "Statue of Unity frame",
    an225MaxTakeoff: "An-225 Mriya max takeoff",
    shuttleWithBooster: "Shuttle with booster",
    heavyTankerLoaded: "Heavy tanker loaded",
    smallTrainComposition: "Small train composition",
    heavyDrillingRig: "Heavy drilling rig",
    belaz75710Loaded: "BelAZ-75710 loaded",
    heavyTransformer: "Heavy transformer",
    liebherrCrane: "Liebherr crawler crane",
    heavyLocomotive4Sections: "Heavy locomotive 4 sections",
    metroTrain8Cars: "Metro train 8 cars",
    zubrHovercraft: "Zubr hovercraft",
    saturn5Rocket: "Saturn V rocket",
    energiaRocket: "Energia rocket",
    smallSteelBridge: "Small steel bridge",
    starshipSuperHeavy: "Starship Super Heavy",
    floatingCraneVolgar: "Floating crane Volgar",
    frigate: "Frigate",
    threeGorgesTurbine: "Three Gorges turbine",
    destroyer: "Destroyer",
    eclipseYachtSmall: "Eclipse yacht small",
    bigBen: "Big Ben",
    eclipseYachtFull: "Eclipse yacht full",
    leaningTowerOfPisa: "Leaning Tower of Pisa",
    smallTanker: "Small tanker",
    stBasilsCathedral: "St. Basil's Cathedral",
    nuclearIcebreakerLenin: "Nuclear icebreaker Lenin",
    nuclearCruiserPyotrVelikiy: "Nuclear cruiser Pyotr Velikiy",
    arcticaIcebreaker: "Arctica icebreaker",
    petroniusPlatformTop: "Petronius platform top",
    vikramadityaAircraftCarrier: "Vikramaditya aircraft carrier",
    mediumTanker: "Medium tanker",
    ostankinoTower: "Ostankino Tower",
    admiralKuznetsovCarrier: "Admiral Kuznetsov carrier",
    queenElizabethCarrier: "Queen Elizabeth carrier",
    goldenGateBridge: "Golden Gate Bridge",
    nimtzCarrier: "Nimitz carrier",
    aframaxTanker: "Aframax tanker",
    knossosPalace: "Knossos Palace",
    suezmaxTanker: "Suezmax tanker",
    colosseum: "Colosseum",
    vlccTanker: "VLCC tanker",
    empireStateBuilding: "Empire State Building",
    ulccTiClassTanker: "ULCC TI class tanker",
    akashiKaikyoBridge: "Akashi Kaikyo Bridge",
    trollAPlatform: "Troll A platform",
    greatWallSection: "Great Wall section",
    pyramidOfKhufu: "Pyramid of Khufu",
    hooverDam: "Hoover Dam",
    totalTonnage: "Total tonnage",
    totalTonnageComparison: "Comparable to: {object}"
  },
  russian: {
    // Settings
    theme: "Тема",
    system: "Системная",
    light: "Светлая",
    dark: "Тёмная",
    weight: "Собственный вес (кг)",
    enterWeight: "Введите вес",
    developerMode: "Режим разработчика",
    importData: "Импорт данных",
    migrateFromOldVersion: "Миграция из старой версии",
    language: "Язык",
    maxMicrohistorySize: "Макс. размер микроистории",
    microhistoryDescription: "Напишите больше, если делаете больше подходов",
    analyticsSettings: "Настройки аналитики",
    visibleMetrics: "Видимые метрики",
    generalTonnage: "Общий тоннаж",
    specificTonnage: "Удельный тоннаж",
    maxWeight: "Максимальный вес",
    maxReps: "Максимальные повторения",
    avgWeight: "Средний вес",
    minWeight: "Минимальный вес",
    workoutTime: "Время тренировки",
    predicted1rm: "Прогнозный 1RM",
    muscleCoefficients: "Коэффициенты крепатуры. Ставьте больше если испытываете сильную крепатуру",
    chest: "Грудь",
    back: "Спина",
    biceps: "Бицепс",
    triceps: "Трицепс",
    delts: "Плечи",
    legs: "Ноги",

    // Calories
    calories: "Калории",
    caloriesPerDay: "Калории за день",
    enterCalories: "Введите количество калорий",
    yourWeight: "Ваш вес (кг)",
    enterYourWeight: "Введите ваш вес",
    save: "Сохранить",
    today: "Сегодня:",
    caloriesValue: "Калории: {value} ккал",
    weightValue: "Вес: {value} кг",
    caloriesAndWeightChart: "График калорий и веса",
    error: "Ошибка",
    fillAllFields: "Заполните все поля",
    enterValidCalories: "Введите корректное количество калорий",
    enterValidWeight: "Введите корректный вес",
    success: "Успех",
    dataSaved: "Данные сохранены",

    // Workout Plan
    selectPlan: "Выберите план",
    noWorkoutsInPlan: "Нет тренировок в плане",
    selectPlanToStart: "Выберите план для начала",
    addWorkout: "+ Добавить тренировку",
    workoutName: "Название тренировки",
    enterName: "Введите название",
    cancel: "Отмена",
    add: "Добавить",
    resultsPlanning: "Планирование результатов",

    // Analytics
    selectExercises: "Выберите упражнения",
    selected: "Выбрано: {count} упражн.",
    date: "Дата",
    tonnage: "Тоннаж",
    weightLabel: "Вес",
    reps: "Повторения",
    minutes: "Минуты",
    t: "т",
    exercise: "Упражнение",
    max: "Макс",
    trend: "Тренд",
    rel: "%",

    // Plan Screen
    addPlannedResult: "Добавить плановый результат",
    weightKg: "Вес (кг)",
    repetitions: "Повторения",
    dateWithinMonth: "Дата (ГГГГ-ММ-ДД)",
    saveResult: "Сохранить",
    monthLabel: "MMMM YYYY",

    // Workout Screen
    editExercise: "Редактировать упражнение",
    addExercise: "Добавить упражнение",
    exerciseName: "Название упражнения",
    comment: "Комментарий",
    timerDurationSec: "Время таймера (сек)",
    muscleGroup: "Группа мышц",
    exerciseType: "Тип упражнения",
    fullAmplitude: "Полная амплитуда",
    partialAmplitude: "Неполная амплитуда",
    unilateral: "Одностороннее",
    bilateral: "Двустороннее",
    machine: "Тренажёр",
    freeWeight: "Свободные веса",
    ownWeight: "Собственный вес",
    cables: "Тросы",
    forearms: "Предплечья",
    glutes: "Ягодицы",
    quads: "Квадрицепсы",
    hamstrings: "Бицепс бедра",
    calves: "Икры",
    abs: "Пресс",
    selectExercise: "Выбери упражнение",

    // Plan Selector
    choosePlan: "Выберите план",
    addPlan: "Добавить план",
    newPlan: "Новый план",
    planName: "Название плана",
    workoutsCount: "{count} тренировок",

    // Exercise Component
    kg: "кг",
    repsUnit: "повторений",
    unilateralExercise: "Одностороннее",
    bilateralExercise: "Двустороннее",
    fullAmplitudeExercise: "Полная амплитуда",
    partialAmplitudeExercise: "Неполная амплитуда",

    // Common
    loading: "Загрузка...",
    loadingData: "Загрузка данных...",
    errorOccurred: "Произошла ошибка",
    tryAgain: "Попробуйте снова",
    confirm: "Подтвердить",
    delete: "Удалить",
    edit: "Редактировать",
    close: "Закрыть",

    // Import Screen
    pasteTextForImport: "Вставьте текст для импорта:",
    selectFile: "Выбрать файл",
    import: "Импортировать",
    dataImportSuccess: "Данные успешно импортированы",
    dataImportError: "Не удалось импортировать данные",
    fileOpenError: "Не удалось открыть файл",
    validationError: "Текст не прошел валидацию",
    importFormatExample: `Вставьте данные в формате:

Жим лежа
60х8 60х7 60х6 01.02.2025
65х8 65х7 65х6 01.03.2025

Подтягивания
10х5 12х4 15х3 01.02.2025

`,

    // Import Validator
    validationErrorTitle: "Ошибка валидации",
    warningTitle: "Предупреждение",

    // Exercise Modal
    chooseExercise: "Выбери упражнение",
    timerDuration: "Время таймера (сек)",

    // Exercise Component
    weightPlaceholder: "Вес",
    repsPlaceholder: "Повторения",

    // Analytics Exercise Selector

    // Tab Navigation
    home: "Главная",
    caloriesTab: "Калории",
    workout: "Тренировка",
    storage: "Хранилище",
    plan: "План",
    analytics: "Аналитика",
    settings: "Настройки",

    // Export
    exportData: "Экспорт данных",
    exportDescription: "Выберите формат для экспорта данных:",
    exportToExcel: "Экспорт в Excel",
    exportToText: "Экспорт в текст",
    exportToPDF: "Экспорт в PDF",
    excelDescription:
      "Excel файл с несколькими листами (планы, результаты, калории)",
    textDescription: "Текстовый файл в авторском формате",
    pdfDescription: "PDF отчёт с графиками и метриками",
    totalSets: "Общее количество подходов",
    dataExportSuccess: "Данные успешно экспортированы",
    dataExportError: "Не удалось экспортировать данные",
    exporting: "Экспорт...",
    notEnoughDataForPDF: "Для экспорта PDF необходимо минимум 10 различных дат",

    // Maintenance Calories
    maintenanceCalories: "Калораж на поддержание",
    maintenanceCaloriesPerDay: "Калории на поддержание веса",
    enterMaintenanceCalories: "Введите калораж на поддержание",
    maintenanceCaloriesSaved: "Калораж на поддержание сохранен",
    enterValidMaintenanceCalories: "Введите корректный калораж на поддержание",
    maintenanceCaloriesValue: "Калораж на поддержание: {value} ккал",
    deviationFromMaintenance: "Отклонение от поддержания: {value} ккал",
    change: "Изменить",
    avgVolume: "Средний тренировочный объем в неделю",
    avgTonnageProgress: "Средний прогресс тоннажа",
    avgWeightProgress: "Средний прогресс в максимальном весе",
    caloriesUp: "Калории (верх)",
    weightDown: "Вес (низ)",
    absMax: "Абсолютный максимум веса",
    trainingSettings: "Настройки тренировки",

    // Comparison objects for total tonnage
    smallAircraftEngine: "Малый авиадвигатель",
    piano: "Рояль",
    fiat500: "Fiat 500",
    safe: "Сейф",
    smartFortwo: "Smart Fortwo",
    ladaGranta: "Лада Гранта",
    boeing737Engine: "Двигатель Boeing 737",
    mazWithCargo: "МАЗ с грузом",
    fordF150: "Ford F-150",
    hummerH1: "Hummer H1",
    kamaz4326: "КамАЗ-4326",
    pazBus: "ПАЗ автобус",
    garbageTruck: "Мусоровоз",
    trolleybus: "Троллейбус",
    bmd4: "БМД-4",
    btr80: "БТР-80",
    bmp2: "БМП-2",
    dumpTruckLoaded: "Самосвал гружёный",
    t34_76: "Танк Т-34/76",
    c130HerculesEmpty: "C-130 Hercules пустой",
    metroCarEmpty: "Вагон метро пустой",
    stonehenge: "Стоунхендж",
    t90: "Танк Т-90",
    boeing757Empty: "Боинг 757 пустой",
    leopard2: "Танк Leopard 2",
    tigerII: "Танк Tiger II",
    boeing767Empty: "Боинг 767 пустой",
    coalWagonLoaded: "Вагон с углём гружёный",
    bulldozerCatD11: "Бульдозер CAT D11",
    tep70Locomotive: "Тепловоз ТЭП70",
    trireme: "Трирема",
    an124Empty: "Ан-124 «Руслан» пустой",
    boeing747Empty: "Боинг 747 пустой",
    mausTank: "Танк «Маус»",
    spacexStarshipPrototype: "SpaceX Starship прототип",
    statueOfLibertyCopper: "Статуя Свободы медь",
    an225Empty: "Ан-225 «Мрия» пустой",
    metroTrain6CarsLoaded: "Состав метро 6 вагонов гружёный",
    boeing747MaxTakeoff: "Боинг 747 макс. взлётный",
    smallSubmarine: "АПЛ малая",
    smallOilPlatform: "Нефтяная платформа малая",
    statueOfUnityFrame: "Статуя Единства каркас",
    an225MaxTakeoff: "Ан-225 «Мрия» макс. взлётный",
    shuttleWithBooster: "Шаттл со стартовым ускорителем",
    heavyTankerLoaded: "Очень тяжёлый танкер-бензовоз гружёный",
    smallTrainComposition: "Локомотив с вагонами (малый состав)",
    heavyDrillingRig: "Буровая установка наземная тяжёлая",
    belaz75710Loaded: "Карьерный самосвал БелАЗ-75710 гружёный",
    heavyTransformer: "Трансформатор сверхтяжёлый",
    liebherrCrane: "Кран гусеничный Liebherr LR 13000 с противовесом",
    heavyLocomotive4Sections: "Очень тяжёлый тепловоз 4 секции",
    metroTrain8Cars: "Вагоны метро полный состав 8 вагонов",
    zubrHovercraft: "Корабль на воздушной подушке Зубр",
    saturn5Rocket: "Ракета-носитель Сатурн-5 стартовая масса",
    energiaRocket: "Ракета-носитель Энергия стартовая масса",
    smallSteelBridge: "Мост малый пролёт стальной",
    starshipSuperHeavy: "Ракета Starship Super Heavy полная заправка",
    floatingCraneVolgar: "Кран плавучий (типа «Волгарь»)",
    frigate: "Фрегат",
    threeGorgesTurbine: "Турбина «Три ущелья»",
    destroyer: "Эсминец",
    eclipseYachtSmall: "Яхта «Eclipse» малая",
    bigBen: "Биг-Бен",
    eclipseYachtFull: "Яхта «Eclipse» полная",
    leaningTowerOfPisa: "Пизанская башня",
    smallTanker: "Танкер малый",
    stBasilsCathedral: "Храм Василия Блаженного",
    nuclearIcebreakerLenin: "Атомный ледокол «Ленин» с корпусами",
    nuclearCruiserPyotrVelikiy: "Атомный крейсер «Пётр Великий»",
    arcticaIcebreaker: "Ледокол «Арктика»",
    petroniusPlatformTop: "Платформа «Petronius» верхнее",
    vikramadityaAircraftCarrier: "Авианосец «Викрамадитья»",
    mediumTanker: "Танкер средний",
    ostankinoTower: "Останкинская башня бетон и металл",
    admiralKuznetsovCarrier: "Авианосец «Адмирал Кузнецов»",
    queenElizabethCarrier: "Авианосец «Куин Элизабет»",
    goldenGateBridge: "Мост «Золотые Ворота» сталь",
    nimtzCarrier: "Авианосец «Нимиц»",
    aframaxTanker: "Супертанкер Aframax",
    knossosPalace: "Кносский дворец",
    suezmaxTanker: "Танкер Suezmax",
    colosseum: "Колизей камень",
    vlccTanker: "Супертанкер VLCC",
    empireStateBuilding: "Эмпайр-стейт-билдинг вес",
    ulccTiClassTanker: "Супертанкер ULCC класс TI",
    akashiKaikyoBridge: "Мост Акаси-Кайкё сталь",
    trollAPlatform: "Платформа «Troll A» основание",
    greatWallSection: "Великая Китайская стена участок",
    pyramidOfKhufu: "Пирамида Хеопса",
    hooverDam: "Плотина Гувера бетон",
    totalTonnage: "Общий тоннаж",
    totalTonnageComparison: "Сравнимо с: {object}"
  },
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.english;

export const getTranslation = (
  language: Language,
  key: TranslationKey,
): string => {
  return translations[language][key];
};

export const formatTranslation = (
  language: Language,
  key: TranslationKey,
  params: Record<string, string | number> = {},
): string => {
  let translation = getTranslation(language, key);

  Object.entries(params).forEach(([param, value]) => {
    translation = translation.replace(`{${param}}`, String(value));
  });

  return translation;
};
